server:
#  port: 8888
  port: ${PORT}

opentracing:
  jaeger:
    http-sender:
#      url: http://localhost:14268/api/traces
      url: http://${JAEGER_HOST}:14268/api/traces
    #enable-b3-propagation: true
spring:
  application:
    name: hello-service

logging:
  level:
    io.opentracing: DEBUG